version: "3"

volumes:
  production_traefik:

services:
  # Redis server for websocket use
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  # Django backend container with WS logic (Django Channels)
  django:
    container_name: backend_django
    build:
      context: .
      dockerfile: ./Dockerfile
    image: backend_django
    depends_on:
      - redis
    ports:
      - "8050:8050"

  # Main container / Vue frontend
  vue_frontend:
    container_name: vue_frontend
    restart: always
    build:
      context: ./outsider-front
      dockerfile: Dockerfile
    image: vue_frontend
    depends_on:
      - django
    expose:
      - 80
  
  # Traefik container for SSL implementation
  traefik:
    container_name: traefik
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    image: traefik_front
    depends_on:
      - django
      - vue_frontend
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
